In [ ]:
import numpy as np

my_array= np.array([1,2,3,4,5])
my_array

type(my_array)

In [ ]:
my_array= np.array((1, 'hi'))
my_array

Creating Arrays

In [ ]:
list_2d= [[1,2],[3,4],[5,6]]
list_2d

array_2d= np.array(list_2d)
array_2d

In-built np methods

In [ ]:
np.linspace(0,10,5)
np.ones((2,2))
np.full((2,2,2), 9)

x= np.random.rand(5,2)
x

x.transpose()
x.mean()
x.astype(int)

In [ ]:
array_1d= np.ones(3)

def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x)

array_2d= np.ones((3,2))
print_array(array_2d)

In [ ]:
array_4d= np.ones((1,2,3,4))
print_array(array_4d)

np 1-d arrays

In [ ]:
x= np.ones(5)
print_array(x)

y= np.ones((1,5))
print_array(y)

z= np.ones((5,1))
print_array(z)

In [ ]:
np.array_equal(x,x)
np.array_equal(x,y)
np.array_equal(y,z)

In [ ]:
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")

Array Operations and Broadcasting

In [ ]:
x+y

In [ ]:
x+y

In [ ]:
y+z

In [60]:
cost= np.array([20, 15, 25])
print("Pie Cost: ")
print(cost)

sales= np.array([[2,3,1],[6,3,3],[5,3,5]])
print("\nPie sales (#):")
print(sales)

total= np.zeros((3,3))
for col in range(sales.shape[1]):
    total[:, col]= sales[:, col]*cost
total

Pie Cost: 
[20 15 25]

Pie sales (#):
[[2 3 1]
 [6 3 3]
 [5 3 5]]


array([[ 40.,  60.,  20.],
       [ 90.,  45.,  45.],
       [125.,  75., 125.]])

In [66]:
cost= np.repeat(cost, 3).reshape((3,3))
cost


array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [67]:

cost*sales

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

In [68]:
cost= np.array([20,25,25]).reshape(3,1)
print(f" cost shape: {cost.shape}")
sales= np.array([[2,3,1], [6,3,3], [5,3,5]])
print(f"sales shape: {sales.shape}")

 cost shape: (3, 1)
sales shape: (3, 3)


In [69]:
sales*cost

array([[ 40,  60,  20],
       [150,  75,  75],
       [125,  75, 125]])

Testing Array compatibility

In [71]:
a= np.ones((3,2))
b= np.ones((3,2,1))
print(f"The shape of a is: {a.shape}")
print(f"The shape of b is: {b.shape}")
print("")
try:
    print(f"The shape of a+b is: {(a+b).shape}")
except:
    print(f"Error: arrays are NOT broadcast compatible")

The shape of a is: (3, 2)
The shape of b is: (3, 2, 1)

Error: arrays are NOT broadcast compatible


Reshaping arrays using
To reshape: .reshape()
To add arrays: np.newaxis/ None
To 'flatten': .ravel()/.flatten()



In [74]:
a= np.ones(3)
print_array(a)
b= np.ones((3,2))
print_array(b)


Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.]
Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [88]:
# add arrays

#add dimensions to a
print_array(a[:, np.newaxis])
print(a[:, None])

# a+b 
a[:, None]+b

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]]


array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [95]:
x= np.full((3,2), 214)
x

# flatten
print_array(x.flatten())
print_array(x.ravel())

Dimensions: 1
     Shape: (6,)
      Size: 6

[214 214 214 214 214 214]
Dimensions: 1
     Shape: (6,)
      Size: 6

[214 214 214 214 214 214]


In [115]:
x= np.random.randint(10, size=(4,6))
x

array([[2, 8, 7, 5, 7, 6],
       [1, 4, 1, 6, 5, 3],
       [0, 3, 8, 4, 5, 6],
       [3, 7, 2, 0, 5, 7]])

In [116]:
x[3,4]

5

In [117]:
x[3][4]

5

In [120]:
# column #2
x[:,2]

x[2:, :3]

array([[0, 3, 8],
       [3, 7, 2]])

In [121]:
x.T

array([[2, 1, 0, 3],
       [8, 4, 3, 7],
       [7, 1, 8, 2],
       [5, 6, 4, 0],
       [7, 5, 5, 5],
       [6, 3, 6, 7]])