"1. Import numpy under alias np."

In [3]:
import numpy as np

"2. Create the following arrays:"

"1. Create an array of 5 zeros."
"2. Create an array of 10 ones."
"3. Create an array of 5 3.141s."
"4. Create an array of integers 1 to 20."
"5. Create a 5x5 matrix of ones with a dtype of int."


In [4]:
"1. Create an array of 5 zeros."
a= np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [5]:
"2. Create an array of 10 ones."
a= np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
"3. Create an array of 5 3.141s."
a= np.full(5, 3.141)
a

array([3.141, 3.141, 3.141, 3.141, 3.141])

In [19]:
"4. Create an array of integers 1 to 20."
a= np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
"5. Create a 5x5 matrix of ones with a dtype of int."
a= np.ones((5, 5), dtype= 'int')
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

"3. Use numpy to: Create a 3D matrix of 3X3X3 from a standard normal distribution."
"Reshape the above array into shape (27,)"

In [22]:
a= np.random.randn(3, 3, 3)
a

array([[[ 0.65726025, -0.35493197, -1.25425124],
        [-2.5660385 ,  2.84624573, -0.62089401],
        [-0.49592693, -0.4280893 ,  0.0289919 ]],

       [[ 0.05673448,  0.1613911 , -1.71545705],
        [-1.34519968,  0.9352574 , -0.17758811],
        [ 0.58532141,  0.56078686, -0.77877799]],

       [[-0.10135666, -0.29019105, -0.18743999],
        [-0.17724238,  0.91616428,  1.70173811],
        [ 0.65030682,  2.10310915, -0.12559546]]])

In [24]:
a= a.reshape(27,)
a

array([ 0.65726025, -0.35493197, -1.25425124, -2.5660385 ,  2.84624573,
       -0.62089401, -0.49592693, -0.4280893 ,  0.0289919 ,  0.05673448,
        0.1613911 , -1.71545705, -1.34519968,  0.9352574 , -0.17758811,
        0.58532141,  0.56078686, -0.77877799, -0.10135666, -0.29019105,
       -0.18743999, -0.17724238,  0.91616428,  1.70173811,  0.65030682,
        2.10310915, -0.12559546])

"4. Create an array of 20 linearly spaced numbers between 1 and 10."

In [118]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

"5. Run the following code to create an array of shape 4x4 and then use indexing to produce the output shown below."

In [122]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
a[3][-1]

20

In [41]:
a[1:, -2:,]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [51]:
a[1]

array([ 6,  7,  8,  9, 10])

In [52]:
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [58]:
a[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

"6. Calculate the sum of all the numbers in a."

In [123]:
asum= np.sum(a)
asum
#a.sum

325

"7. Calculate the sum of each row in a."

In [ ]:
print (np.sum(a[0]))
print (np.sum(a[1]))
print (np.sum(a[2]))
print (np.sum(a[3]))
print (np.sum(a[4]))
         #a.sum(axis=1)    

In [136]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

"8. Extract all the values of a greater than the mean of a."

In [130]:
a[a > a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

"9. Find the location of the minimum value in the following array b."

In [80]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [ ]:
np.argwhere(b.min()==b)
#b.argmin()

In [135]:
b.argmin()

6

"10. Find the location of the maximum value in the following 2D array c."

In [83]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [ ]:
np.argwhere(c.max()==c)
#np.unravel_index(c.argmax(), c.shape)

In [134]:
print (np.unravel_index(c.argmax(), c.shape))
print (c.max())

(2, 1)
1.651436537097151
